### ISSUE TITLE
AES-NI to slow

### ISSUE THREAD

**Issue by t2d** [dlitz/pycrypto#101]
Today I did a test and encryped as many blocks as possible with AES.
The numbers variate around almost the same amount, whether I use `use_aesni=True` or `use_aesni=False`.
I checked with `python -v` and _AESNI.c is loaded at runtime.
How can that be?
If I test with `openssl speed` AESNI is up to 6 times faster than plain AES.

**Comment by dlitz** [comment]
What does your test code look like?  Are you passing a large buffer to `.encrypt(...)`, or are you invoking `.encrypt(...)` many times with small buffers?  The latter is slow simply because of the Python interpreter's overhead.

**Comment by t2d** [comment]
yes, it was a lot of small ones. Thanks for the clarification.
