### ISSUE TITLE
RC4 implementation vulnerable

### ISSUE THREAD

**Issue by AbhiKafle123** [dlitz/pycrypto#189]
PyCrypto's RC4 does not throw away any of the initial bytes of the RC4 keystream, which is a security weakness. In practice, the first 3000 bytes should be removed.

**Comment by dlitz** [comment]
The ARC4 module is a raw crypto primitive.  It can't just throw away some arbitrary number of bytes without breaking interoperability.

Throwing away bytes before encryption is trivial:

```python
cipher = ARC4.new(key)
cipher.encrypt("\0" * 3000)    # Throw away first 3000 bytes
ciphertext = cipher.encrypt(plaintext)
```
