### ISSUE TITLE
build issues for AIX 5.3 and 6.1 - pycrypto-2.6.1

### ISSUE THREAD

**Issue by aixtools** [dlitz/pycrypto#209]
Thought I had submitted information yesterday - so short version today.

My system: AIX 5.3 and AIX 6.1, python 2.7.12, xlc v11 (sp20)

Issues:
- needs CFLAGS=-D_LARGE_FILES
- CFLAGS -std=c99 only works (guessing) for gcc. For xlc generates a warning

While configure sees that GNU malloc is not available src/config.h still has #define malloc rpl_malloc and link/shared library creation fails with rpl_malloc not found.

Note: as long as configure continues to include #define malloc rpl_malloc "pip install" of pycrypto will be impossible. A possible solution is to #undef malloc in src/AES.c when building on AIX, e.g.,
 #ifdef _AIX
 #undef malloc
 #endif

FYI: the _LARGE_FILES define exists since 1997-1998 time frame - to permit >32-bit files (aka "64-bit" files) in 32-bit applications and/or kernel - as well as 64-bit applications. While - imho - it is beter if it is included in the "configure" output - it is sufficient to export CFLAGS="-D_LARGE_FILES" before calling 'pip install'

**Comment by aixtools** [comment]
I found a way to fix the CFLAGS issue, but on my pre-test, it seems to not be an issue I can re-create. I expect it is a different module I was building in parallel - and I shall post there.

As the PR moves forward (see #212) this may be closed.

**Comment by Varbin** [comment]
Please see #238.
