### ISSUE TITLE
python setup.py check results for AIX - FYI

### ISSUE THREAD

**Issue by aixtools** [dlitz/pycrypto#210]
root@x064:[/data/prj/aixtools/saltstack/pycrypto-2.6.1]python setup.py test
running test
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F..E...E.E...........................................................................................................FF.F..F..FF..............................................SelfTest: You can ignore the RandomPool_DeprecationWarning that follows.
# ..........E..............F..F.
## ERROR: testDecrypt1 (Crypto.SelfTest.Cipher.test_pkcs1_oaep.PKCS1_OAEP_Tests)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py", line 304, in testDecrypt1
    pt = cipher.decrypt(t2b(test[2]))
  File "build/lib.aix-5.3-2.7/Crypto/Cipher/PKCS1_OAEP.py", line 227, in decrypt
    raise ValueError("Incorrect decryption.")
ValueError: Incorrect decryption.
# 
## ERROR: testEncryptDecrypt1 (Crypto.SelfTest.Cipher.test_pkcs1_oaep.PKCS1_OAEP_Tests)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py", line 337, in testEncryptDecrypt1
    self.assertEqual(cipher.decrypt(ct), pt)
  File "build/lib.aix-5.3-2.7/Crypto/Cipher/PKCS1_OAEP.py", line 227, in decrypt
    raise ValueError("Incorrect decryption.")
ValueError: Incorrect decryption.
# 
## ERROR: testEncryptDecrypt3 (Crypto.SelfTest.Cipher.test_pkcs1_oaep.PKCS1_OAEP_Tests)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py", line 361, in testEncryptDecrypt3
    self.assertEqual(cipher.decrypt(ct), pt)
  File "build/lib.aix-5.3-2.7/Crypto/Cipher/PKCS1_OAEP.py", line 227, in decrypt
    raise ValueError("Incorrect decryption.")
ValueError: Incorrect decryption.
# 

ERROR: test_negative_number_roundtrip_mpzToLongObj_longObjToMPZ (Crypto.SelfTest.Util.test_number.MiscTests)
## Test that mpzToLongObj and longObjToMPZ (internal functions) roundtrip negative numbers correctly.

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Util/test_number.py", line 283, in test_negative_number_roundtrip_mpzToLongObj_longObjToMPZ
    k = number._fastmath.rsa_construct(n, e)
AttributeError: 'NoneType' object has no attribute 'rsa_construct'
# 
## FAIL: testEncryptVerify1 (Crypto.SelfTest.Cipher.test_pkcs1_15.PKCS1_15_Tests)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Cipher/test_pkcs1_15.py", line 162, in testEncryptVerify1
    self.assertEqual(pt,pt2)
AssertionError: '\x06w\xfb' != '---'
# 

FAIL: test_construct_3tuple (Crypto.SelfTest.PublicKey.test_RSA.RSATest)
## RSA (default implementation) constructed key (3-tuple)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 144, in test_construct_3tuple
    self._check_signing(rsaObj)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 317, in _check_signing
    self.assertEqual((signature,), rsaObj.sign(message, b("")))
AssertionError: Tuples differ: (64592789325039501171926360509... != (13135072118873791480329014862...

First differing element 0:
645927893250395011719263605099768183701819230087467845571079950109217122675495664526021440747459541876126146644231555580995560008050170267480896637301769327836379684977618019732684632542400281836505723620197302560033329765408403885679453715528212973349952504137496279620162742258648932773292837516799721005L
131350721188737914803290148626506641815170189237132888858909578256220768895065929928213577344153687948386572136620970592012822366543948287668736833346742150550965326927146321358757154944818941195651869895653484220754508100473030340977696886103470280817120375117170036361658306515165246580084160510385937563532L
- (645927893250395011719263605099768183701819230087467845571079950109217122675495664526021440747459541876126146644231555580995560008050170267480896637301769327836379684977618019732684632542400281836505723620197302560033329765408403885679453715528212973349952504137496279620162742258648932773292837516799721005L,)
- (131350721188737914803290148626506641815170189237132888858909578256220768895065929928213577344153687948386572136620970592012822366543948287668736833346742150550965326927146321358757154944818941195651869895653484220754508100473030340977696886103470280817120375117170036361658306515165246580084160510385937563532L,)
# 

FAIL: test_construct_4tuple (Crypto.SelfTest.PublicKey.test_RSA.RSATest)
## RSA (default implementation) constructed key (4-tuple)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 152, in test_construct_4tuple
    self._check_signing(rsaObj)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 317, in _check_signing
    self.assertEqual((signature,), rsaObj.sign(message, b("")))
AssertionError: Tuples differ: (64592789325039501171926360509... != (13135072118873791480329014862...

First differing element 0:
645927893250395011719263605099768183701819230087467845571079950109217122675495664526021440747459541876126146644231555580995560008050170267480896637301769327836379684977618019732684632542400281836505723620197302560033329765408403885679453715528212973349952504137496279620162742258648932773292837516799721005L
131350721188737914803290148626506641815170189237132888858909578256220768895065929928213577344153687948386572136620970592012822366543948287668736833346742150550965326927146321358757154944818941195651869895653484220754508100473030340977696886103470280817120375117170036361658306515165246580084160510385937563532L
- (645927893250395011719263605099768183701819230087467845571079950109217122675495664526021440747459541876126146644231555580995560008050170267480896637301769327836379684977618019732684632542400281836505723620197302560033329765408403885679453715528212973349952504137496279620162742258648932773292837516799721005L,)
- (131350721188737914803290148626506641815170189237132888858909578256220768895065929928213577344153687948386572136620970592012822366543948287668736833346742150550965326927146321358757154944818941195651869895653484220754508100473030340977696886103470280817120375117170036361658306515165246580084160510385937563532L,)
# 

FAIL: test_construct_6tuple (Crypto.SelfTest.PublicKey.test_RSA.RSATest)
## RSA (default implementation) constructed key (6-tuple)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 169, in test_construct_6tuple
    self._check_decryption(rsaObj)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 289, in _check_decryption
    self.assertEqual(b2a_hex(plaintext), b2a_hex(new_plaintext))
AssertionError: 'eb7a19ace9e3006350e329504b45e2ca82310b26dcd87d5c68f1eea8f55267c31b2e8bb4251f84d7e0b2c04626f5aff93edcfb25c9c2b3ff8ae10e839a2ddb4cdcfe4ff47728b4a1b7c1362baad29ab48d2869d5024121435811591be392f982fb3e87d095aeb40448db972f3ac14f7bc275195281ce32d2f1b76d4d353e2d' != '9025bf111df7c601976e49b52bb276b70833d3fec6fe45013d7e04f4b61ba5437da504dca52b113e5d704c2a7716d77eb09c0b1aa41f68e201b990383cf0bfd2533df359ac386b521720d709c1327d6c783ae3ea1404d07b845e2f721135ed08c3633b0f0d456b4d4248f85170485b4399db385f8b3e332f2b7a875892550f30'
# 

FAIL: test_generate_2arg (Crypto.SelfTest.PublicKey.test_RSA.RSATest)
## RSA (default implementation) generated key (2 arguments)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 118, in test_generate_2arg
    self._exercise_primitive(rsaObj)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 261, in _exercise_primitive
    self.assertEqual((bytes_to_long(plaintext),), signature2)
AssertionError: Tuples differ: (52812943483972624298859104134... != (60097669670999401097172080480...

First differing element 0:
52812943483972624298859104134960189106119393598487484673100830327269219954674294714443274154657664096752404840776693219936282860139270406849773736755668258959619038833229158750249419975033421837647822438923541713787478734260064294340334577071780196079609817963478693512438777918894696854225793439857265006634L
60097669670999401097172080480329013255733173273873328548713897578969087543039534589407257263959263104653813383385909446419762409512735489469670049136099313602582245100092309193830909427731406188975134120108687159585593703509825726776915120285786731204532262148429523405893312431924121845941636883951761666109L
- (52812943483972624298859104134960189106119393598487484673100830327269219954674294714443274154657664096752404840776693219936282860139270406849773736755668258959619038833229158750249419975033421837647822438923541713787478734260064294340334577071780196079609817963478693512438777918894696854225793439857265006634L,)
- (60097669670999401097172080480329013255733173273873328548713897578969087543039534589407257263959263104653813383385909446419762409512735489469670049136099313602582245100092309193830909427731406188975134120108687159585593703509825726776915120285786731204532262148429523405893312431924121845941636883951761666109L,)
# 

FAIL: test_construct_3tuple (Crypto.SelfTest.PublicKey.test_RSA.RSASlowMathTest)
## RSA (_slowmath implementation) constructed key (3-tuple)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 374, in test_construct_3tuple
    RSATest.test_construct_3tuple(self)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 143, in test_construct_3tuple
    self._check_decryption(rsaObj)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 289, in _check_decryption
    self.assertEqual(b2a_hex(plaintext), b2a_hex(new_plaintext))
AssertionError: 'eb7a19ace9e3006350e329504b45e2ca82310b26dcd87d5c68f1eea8f55267c31b2e8bb4251f84d7e0b2c04626f5aff93edcfb25c9c2b3ff8ae10e839a2ddb4cdcfe4ff47728b4a1b7c1362baad29ab48d2869d5024121435811591be392f982fb3e87d095aeb40448db972f3ac14f7bc275195281ce32d2f1b76d4d353e2d' != '259e6143fff6c528cf153ce1b90f1d4296ffdfa1e7e6745c82a0262c54a3de7b19f9432b1fc3e79c59b0f19e8c42651c1a56ae9143644255e387f61f8095952979a4ba32f461d44943ab85eb08bb81b3ab4fe91d14230d0aca00873412628edca01df7aff0722d2044326e304a56960a61dba02c299166509e5edd93e22f143a'
# 

FAIL: test_construct_4tuple (Crypto.SelfTest.PublicKey.test_RSA.RSASlowMathTest)
## RSA (_slowmath implementation) constructed key (4-tuple)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 378, in test_construct_4tuple
    RSATest.test_construct_4tuple(self)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 152, in test_construct_4tuple
    self._check_signing(rsaObj)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/PublicKey/test_RSA.py", line 317, in _check_signing
    self.assertEqual((signature,), rsaObj.sign(message, b("")))
AssertionError: Tuples differ: (64592789325039501171926360509... != (13135072118873791480329014862...

First differing element 0:
645927893250395011719263605099768183701819230087467845571079950109217122675495664526021440747459541876126146644231555580995560008050170267480896637301769327836379684977618019732684632542400281836505723620197302560033329765408403885679453715528212973349952504137496279620162742258648932773292837516799721005L
131350721188737914803290148626506641815170189237132888858909578256220768895065929928213577344153687948386572136620970592012822366543948287668736833346742150550965326927146321358757154944818941195651869895653484220754508100473030340977696886103470280817120375117170036361658306515165246580084160510385937563532L
- (645927893250395011719263605099768183701819230087467845571079950109217122675495664526021440747459541876126146644231555580995560008050170267480896637301769327836379684977618019732684632542400281836505723620197302560033329765408403885679453715528212973349952504137496279620162742258648932773292837516799721005L,)
- (131350721188737914803290148626506641815170189237132888858909578256220768895065929928213577344153687948386572136620970592012822366543948287668736833346742150550965326927146321358757154944818941195651869895653484220754508100473030340977696886103470280817120375117170036361658306515165246580084160510385937563532L,)
# 
## FAIL: testSignVerify (Crypto.SelfTest.Signature.test_pkcs1_15.PKCS1_15_Tests)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Signature/test_pkcs1_15.py", line 207, in testSignVerify
    self.failUnless(result)
AssertionError: False is not true
# 
## FAIL: testSignVerify (Crypto.SelfTest.Signature.test_pkcs1_pss.PKCS1_PSS_Tests)

Traceback (most recent call last):
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/Signature/test_pkcs1_pss.py", line 406, in testSignVerify
    self.failUnless(signer.verify(h, s))
AssertionError: False is not true

---

Ran 1033 tests in 61.726s

FAILED (failures=9, errors=4)
Traceback (most recent call last):
  File "setup.py", line 456, in <module>
    core.setup(**kw)
  File "/opt/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 336, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build/lib.aix-5.3-2.7/Crypto/SelfTest/**init**.py", line 74, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=1033 errors=4 failures=9>)

**Comment by Varbin** [comment]
1. For future bug reports use formatting.
2. Please see #238.

**Comment by aixtools** [comment]
... use formatting.
Sigh - yet another mountain to climb ;)
