### ISSUE TITLE
unable to install/build on windows/error with Visual C++

### ISSUE THREAD

**Issue by rjshaver** [dlitz/pycrypto#221]
I have been trying to install/build pycrypto on my laptop and have had problems that I cannot determine a solution.  My laptop is running Windows 10 and I have multiple versions of python and Visual Studio.  Python versions: 2.7, 3.5 and 3.6 (plus a couple of Iron Python versions); Visual Studio 2015, 2017 Community, and 2017 Community Preview.  I first tried to install into the Python 2.7 using pip.  I had to add the Visual C++ for Python 2.7, but it did install using pip.  Then, I went to add it to my Python 3.6 install and have not been able to figure out why it will not install.  I first tried pip, but when that did not work, I checked your installation section of this github repository.  It  looks like a problem with Visual C++.   I ended up putting the ouput of python setup.py build into a file which I have included.  I got a couple of errors from the command line listed here:

> warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

Can anyone advise so that I can get this installed and use it in another program?  Thanks!

[builderror.txt](https://github.com/dlitz/pycrypto/files/852694/builderror.txt)

**Comment by pfmoore** [comment]
The issue appears to be with the supplied ```src\inc-msvc\stdint.h``` file, which is incomplete. For Python 3.6 this isn't needed.

The simplest fix is to comment out the line

```python
            self.compiler.include_dirs.insert(0, "src/inc-msvc/")
```

from ```setup.py```. Obviously a "proper" fix would need to omit this conditional on the build being for Python 3.6 or later.

**Comment by Varbin** [comment]
Please see #238.

**Comment by rjshaver** [comment]
moved to pycryptodome.  Thx.

**Comment by raffam** [comment]
Why this is closed? It the 10th of Aprile 2019 and I still have this issue
I reached this issue by lokking in google and finding [this](https://stackoverflow.com/questions/41843266/microsoft-windows-python-3-6-pycrypto-installation-error)

**Comment by njuicsgz** [comment]
I tried to install pycryptodome, but it has other problems.
