### ISSUE TITLE
Cannot install package under Windows

### ISSUE THREAD

**Issue by symonsoft** [dlitz/pycrypto#281]
> winrand.c
>     C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(27): error C2061: syntax error: identifier 'intmax_t'
>     C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\inttypes.h(28): error C2061: syntax error: identifier 'rem'
>    ....

and so on,...

**Comment by DennisAng** [comment]
PyCrypto is no longer maintained (#238). You can try [PyCryptodome](https://github.com/Legrandin/pycryptodome) instead.
